In [1]:
import numpy as np

## Exercise 1

In [2]:
X = np.array(
    [[1, 1, 1],
     [1.5, 2, 0],
     [-0.5, 0, -3],
     [0, -0.5, -1]]
)

###  Sub-question (a)

Using $n$ data points, given by the rows in the matrix $X \in \mathbb{R}^{n x p}$, we want to determine $k$ clusters. The cent
roids of those clusters are the rows in the matrix $R \in \mathbb{R}^{k x n}$.

In [3]:
def f(R):
    indicators = np.zeros((4, 2))
    for i, row in enumerate(X):
        mat = np.tile(row, (R.shape[0], 1))
        norms = np.linalg.norm(R - mat, axis=1)
        indicators[i, :] = (norms == norms.max()).astype(int)

    return indicators

In [4]:
R0 = np.array(
    [[3, 3, 3],
     [-1, -1, 0]]
)

In [5]:
R1 = np.array(
    [[1 / 6, 1 / 6, -1],
     [1.5, 2, 0]]
)

In [6]:
R2 = np.array(
    [[2.5 / 2, 3 / 2, 1 / 2],
     [-1 / 4, -1 / 4, -2]]
)

In [7]:
R3 = np.array(
    [[-1 / 4, -1 / 4, -2],
     [2.5 / 2, 3 / 2, 1 / 2]]
)

In [8]:
print(f"""
Indicator vectors #1:

{f(R0)}

Indicator vectors #2:

{f(R1)}

Indicator vectors #3:

{f(R2)}

Indicator vectors #4:

{f(R3)}
"""
      )


Indicator vectors #1:

[[1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]

Indicator vectors #2:

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]

Indicator vectors #3:

[[0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]

Indicator vectors #4:

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]



Sub-question (b)

In [9]:
R0 = np.array(
    [[-0.5, 0, -3],
     [-1, -1, 1]]
)

In [10]:
R1 = np.array(
    [[5 / 4, 3 / 2, 1 / 2],
     [-1 / 4, -1 / 4, -2]]
)

In [11]:
R2 = np.array(
    [[-1 / 4, -1 / 4, -2],
     [5 / 4, 3 / 2, 1 / 2]]
)

In [12]:
print(f"""
Indicator vectors #1:

{f(R0)}

Indicator vectors #2:

{f(R1)}

Indicator vectors #3:

{f(R2)}
"""
      )


Indicator vectors #1:

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]

Indicator vectors #2:

[[0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]

Indicator vectors #3:

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]



Verify with scikit-learn

In [13]:
from sklearn.cluster import KMeans

In [14]:
def _get_kmeans_labels(X, init):
    km = KMeans(n_clusters=2, init=init, n_init=1).fit(X)
    return km.labels_, km.n_iter_

In [15]:
R0 = np.array(
    [[3, 3, 3],
     [-1, -1, 0]]
)
labels, iters = _get_kmeans_labels(X, R0)
print(f"""
Clusters: {labels}
N iterations to get there: {iters}
""")


Clusters: [0 0 1 1]
N iterations to get there: 3



In [16]:
R0 = np.array(
    [[-0.5, 0, -3],
     [-1, -1, 1]]
)
_get_kmeans_labels(X, R0)
labels, iters = _get_kmeans_labels(X, R0)
print(f"""
Clusters: {labels}
N iterations to get there: {iters}
""")


Clusters: [1 1 0 0]
N iterations to get there: 2

