In [44]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

# Exercise 2

In [70]:
n0 = 5; p = 3; c = 2
np.random.seed(0)
A1 = np.random.randn(n0,p) + c * np.array([1,0,0])
A2 = np.random.randn(n0,p) + c * np.array([0,1,0])
A3 = np.random.randn(n0,p) + c * np.array([0,0,1])
A4 = np.array([[0,0,0]])
A = np.concatenate((A1,A2,A3,A4))
print(A)

[[ 3.76405235  0.40015721  0.97873798]
 [ 4.2408932   1.86755799 -0.97727788]
 [ 2.95008842 -0.15135721 -0.10321885]
 [ 2.4105985   0.14404357  1.45427351]
 [ 2.76103773  0.12167502  0.44386323]
 [ 0.33367433  3.49407907 -0.20515826]
 [ 0.3130677   1.14590426 -2.55298982]
 [ 0.6536186   2.8644362  -0.74216502]
 [ 2.26975462  0.54563433  0.04575852]
 [-0.18718385  3.53277921  1.46935877]
 [ 0.15494743  0.37816252  1.11221425]
 [-1.98079647 -0.34791215  2.15634897]
 [ 1.23029068  1.20237985  1.61267318]
 [-0.30230275 -1.04855297  0.57998206]
 [-1.70627019  1.9507754   1.49034782]
 [ 0.          0.          0.        ]]


## A)

In [85]:
Dist = np.sqrt(np.sum((A[:, None, :] - A[None, :, :])**2, axis=2))
epsilon = 2.5
G = 1*(Dist <= epsilon) - np.eye(Dist.shape)
print(G)
G = nx.from_numpy_matrix(G)
nx.draw(G, with_labels=True, pos=nx.circular_layout(G))

# Show the plot
plt.show()




TypeError: 'tuple' object is not callable